<?php

namespace AppBundle\Repository;

/**
 * bookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bookRepository extends \Doctrine\ORM\EntityRepository
{
}
